on:
  issues:
    types:
      - labeled
      - edited

jobs:
  issue_to_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: eunjae-lee/issue-to-markdown@v1.1.0
        with:
          use_custom_path: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          dest: "pages"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update contents"
